version: '3.9'

x-variables: &variables
  DB_NAME: postgres_db
  DB_USER: user
  DB_PASSWORD: password

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/variables.DB_NAME
      SPRING_DATASOURCE_USERNAME: variables.DB_USER
      SPRING_DATASOURCE_PASSWORD: variables.DB_PASSWORD
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: variables.DB_USER
      POSTGRES_PASSWORD: variables.DB_PASSWORD
      POSTGRES_DB: variables.DB_NAME
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: